version: "3.6"
services: 
    hinghwadict-backend:
        build: .
        image: "sheeplin/${SERVICE_NAME}"
        container_name: "${SERVICE_NAME}"
        restart: unless-stopped
        labels: 
            - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_ADDRESS}`)"
            - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8000"
            - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
            - "traefik.http.routers.${SERVICE_NAME}.tls=true"
            - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=tencentcloud"
            - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-compress"
            - "traefik.http.middlewares.${SERVICE_NAME}-compress.compress=true"
        networks: 
            - traefik-global-proxy
        volumes:
           - ../../data/db.sqlite3:/usr/src/HinghwaDict-backend/db.sqlite3
           - ../../data/media:/usr/src/HinghwaDict-backend/media
           - ../../data/logs:/usr/src/HinghwaDict-backend/logs
networks:
  traefik-global-proxy:
    external: true
