version: "3.6"
services: 
    hinghwadict-backend:
        build: .
        image: sheeplin/hinghwadict-backend-test
        container_name: hinghwadict-backend-test
        # ports: 
        #     - "80:8000"
        labels: 
            - "traefik.http.routers.hinghwadict-backend-test.rule=Host(`api.pxm.test.edialect.top`)"
            - "traefik.http.services.hinghwadict-backend-test.loadbalancer.server.port=8000"
            - "traefik.http.routers.hinghwadict-backend-test.entrypoints=websecure"
            - "traefik.http.routers.hinghwadict-backend-test.tls=true"
            - "traefik.http.routers.hinghwadict-backend-test.middlewares=hinghwadict-backend-test-compress"
            - "traefik.http.middlewares.hinghwadict-backend-test-compress.compress=true"
        networks: 
            - traefik-global-proxy
        volumes:
           - ../../data/db.sqlite3:/usr/src/HinghwaDict-backend/db.sqlite3
           - ../../data/media:/usr/src/HinghwaDict-backend/media
           - ../../data/logs:/usr/src/HinghwaDict-backend/logs
networks:
  traefik-global-proxy:
    external: true
