version: "3.6"
services: 
    hinghwadict-backend:
        build: .
        image: sheeplin/hinghwadict-backend
        container_name: hinghwadict-backend
        # ports: 
        #     - "80:8000"
        labels: 
            - "traefik.http.routers.hinghwadict-backend.rule=Host(`api.pxm.edialect.top`)"
            - "traefik.http.services.hinghwadict-backend.loadbalancer.server.port=8000"
            - "traefik.http.routers.hinghwadict-backend.entrypoints=websecure"
            - "traefik.http.routers.hinghwadict-backend.tls=true"
            - "traefik.http.routers.hinghwadict-backend.middlewares=hinghwadict-backend-compress"
            - "traefik.http.middlewares.hinghwadict-backend-compress.compress=true"
        networks: 
            - traefik-global-proxy
        volumes:
           - ../../data/db.sqlite3:/usr/src/HinghwaDict-backend/db.sqlite3
           - ../../data/media:/usr/src/HinghwaDict-backend/media
           - ../../data/logs:/usr/src/HinghwaDict-backend/logs
networks:
  traefik-global-proxy:
    external: true
